export enum Role {
  SYSADMIN = 'SYSADMIN',
  CLIENT_ADMIN='CLIENT_ADMIN',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  SITE_MANAGER = 'SITE_MANAGER',
  QS_ENGINEER='QS_ENGINEER',
  SITE_ENGINEER='SITE_ENGINEER',
  
 

}
